<?php

declare(strict_types=1);

namespace Rlorenzo\MagoWordPress\Internal\WordPress;

/**
 * Whether phpcs reports each message code of the sniffs this package ports as an error or a
 * warning, from WordPress Coding Standards 3.4.1 and the phpcs/PHPCSExtra sniffs it pulls in.
 *
 * Generated by bin/generate-lists.php from each sniff's `addError()` / `addWarning()` /
 * `addMessage($isError)` calls, its `getGroups()` types and the WordPress rulesets' `<type>`
 * overrides — do not hand-edit.
 *
 * @internal
 */
final class Levels
{
    /**
     * Sniff => message code (`*` matches any text) => `error`, `warning`, or `error|warning`
     * when the sniff decides at runtime (deprecations against `minimum_wp_version`, dynamic names).
     *
     * @var array<string, array<string, 'error'|'warning'|'error|warning'>>
     */
    public const SNIFFS = [
        'Generic.CodeAnalysis.AssignmentInCondition' => [
            'Found' => 'warning',
            'FoundInWhileCondition' => 'warning',
        ],
        'Generic.CodeAnalysis.EmptyPHPStatement' => [
            'EmptyPHPOpenCloseTagsDetected' => 'warning',
            'SemicolonWithoutCodeDetected' => 'warning',
        ],
        'Generic.CodeAnalysis.ForLoopShouldBeWhileLoop' => [
            'CanSimplify' => 'warning',
        ],
        'Generic.CodeAnalysis.ForLoopWithTestFunctionCall' => [
            'NotAllowed' => 'warning',
        ],
        'Generic.CodeAnalysis.JumbledIncrementer' => [
            'Found' => 'warning',
        ],
        'Generic.CodeAnalysis.RequireExplicitBooleanOperatorPrecedence' => [
            'MissingParentheses' => 'error',
        ],
        'Generic.CodeAnalysis.UnconditionalIfStatement' => [
            'Found' => 'warning',
        ],
        'Generic.CodeAnalysis.UnnecessaryFinalModifier' => [
            'Found' => 'warning',
        ],
        'Generic.CodeAnalysis.UselessOverridingMethod' => [
            'Found' => 'warning',
        ],
        'Generic.Files.ByteOrderMark' => [
            'Found' => 'error',
        ],
        'Generic.Files.OneObjectStructurePerFile' => [
            'MultipleFound' => 'error',
        ],
        'Generic.NamingConventions.UpperCaseConstantName' => [
            'ClassConstantNotUpperCase' => 'error',
            'ConstantNotUpperCase' => 'error',
        ],
        'Generic.PHP.BacktickOperator' => [
            'Found' => 'error',
        ],
        'Generic.PHP.DisallowAlternativePHPTags' => [
            'ASPOpenTagFound' => 'error',
            'ASPShortOpenTagFound' => 'error',
            'MaybeASPOpenTagFound' => 'warning',
            'MaybeASPShortOpenTagFound' => 'warning',
            'ScriptOpenTagFound' => 'error',
        ],
        'Generic.PHP.DisallowShortOpenTag' => [
            'EchoFound' => 'error',
            'Found' => 'error',
            'PossibleFound' => 'warning',
        ],
        'Generic.PHP.DiscourageGoto' => [
            'Found' => 'warning',
        ],
        'Generic.PHP.ForbiddenFunctions' => [
            '*' => 'error',
            '*WithAlternative' => 'error|warning',
            'Discouraged' => 'error|warning',
            'Found' => 'error|warning',
        ],
        'Generic.PHP.LowerCaseConstant' => [
            'Found' => 'error',
        ],
        'Generic.PHP.LowerCaseKeyword' => [
            'Found' => 'error',
        ],
        'Generic.PHP.LowerCaseType' => [
            '*' => 'error',
        ],
        'Generic.Strings.UnnecessaryStringConcat' => [
            'Found' => 'error|warning',
        ],
        'Generic.VersionControl.GitMergeConflict' => [
            'CloserFound' => 'error',
            'DelimiterFound' => 'error',
            'OpenerFound' => 'error',
        ],
        'PEAR.NamingConventions.ValidClassName' => [
            'Invalid' => 'error',
            'StartWithCapital' => 'error',
        ],
        'PSR2.Classes.PropertyDeclaration' => [
            'AbstractAfterVisibility' => 'error',
            'AvizKeywordOrder' => 'error',
            'FinalAfterVisibility' => 'error',
            'Multiple' => 'error',
            'ReadonlyBeforeVisibility' => 'error',
            'ScopeMissing' => 'error',
            'SpacingAfterType' => 'error',
            'StaticBeforeVisibility' => 'error',
            'Underscore' => 'warning',
            'VarUsed' => 'error',
        ],
        'PSR2.Files.ClosingTag' => [
            'NotAllowed' => 'error',
        ],
        'Squiz.Classes.SelfMemberReference' => [
            'IncorrectCase' => 'error',
            'NotUsed' => 'error',
            'SpaceAfter' => 'error',
            'SpaceBefore' => 'error',
        ],
        'Squiz.PHP.DisallowMultipleAssignments' => [
            '*InControlStructure' => 'error',
            'Found' => 'error',
        ],
        'Squiz.PHP.DisallowSizeFunctionsInLoops' => [
            'Found' => 'error',
        ],
        'Squiz.PHP.Eval' => [
            'Discouraged' => 'error',
        ],
        'Squiz.Scope.MethodScope' => [
            'Missing' => 'error',
        ],
        'Universal.Arrays.DisallowShortArraySyntax' => [
            'Found' => 'error',
        ],
        'Universal.CodeAnalysis.ForeachUniqueAssignment' => [
            'NotUnique' => 'error',
        ],
        'Universal.Operators.DisallowShortTernary' => [
            'Found' => 'error',
        ],
        'WordPress.CodeAnalysis.AssignmentInTernaryCondition' => [
            'FoundInTernaryCondition' => 'warning',
        ],
        'WordPress.CodeAnalysis.EscapedNotTranslated' => [
            'Found' => 'warning',
        ],
        'WordPress.DB.DirectDatabaseQuery' => [
            'DirectQuery' => 'warning',
            'NoCaching' => 'warning',
            'SchemaChange' => 'warning',
        ],
        'WordPress.DB.PreparedSQL' => [
            'InterpolatedNotPrepared' => 'error',
            'NotPrepared' => 'error',
        ],
        'WordPress.DB.PreparedSQLPlaceholders' => [
            'IdentifierWithinIN' => 'error',
            'LikeWildcardsInQuery' => 'error',
            'LikeWildcardsInQueryWithPlaceholder' => 'error',
            'LikeWithoutWildcards' => 'warning',
            'MissingReplacements' => 'error',
            'QuotedDynamicPlaceholderGeneration' => 'error',
            'QuotedIdentifierPlaceholder' => 'error',
            'QuotedSimplePlaceholder' => 'error',
            'ReplacementsWrongNumber' => 'warning',
            'UnescapedLiteral' => 'error',
            'UnfinishedPrepare' => 'warning',
            'UnnecessaryPrepare' => 'warning',
            'UnquotedComplexPlaceholder' => 'warning',
            'UnsupportedIdentifierPlaceholder' => 'error',
            'UnsupportedPlaceholder' => 'error',
        ],
        'WordPress.DB.RestrictedClasses' => [
            'mysql_*' => 'error',
        ],
        'WordPress.DB.RestrictedFunctions' => [
            'mysql_*' => 'error',
        ],
        'WordPress.DB.SlowDBQuery' => [
            'slow_db_query_*' => 'warning',
        ],
        'WordPress.DateTime.CurrentTimeTimestamp' => [
            'Requested' => 'warning',
            'RequestedUTC' => 'error',
        ],
        'WordPress.DateTime.RestrictedFunctions' => [
            'date_*' => 'error',
            'timezone_change_*' => 'error',
        ],
        'WordPress.Files.FileName' => [
            'InvalidClassFileName' => 'error',
            'InvalidTemplateTagFileName' => 'error',
            'NotHyphenatedLowercase' => 'error',
        ],
        'WordPress.NamingConventions.PrefixAllGlobals' => [
            'DynamicHooknameFound' => 'error|warning',
            'ForbiddenPrefixPassed' => 'error',
            'InvalidPrefixPassed' => 'warning',
            'NonPrefixedClassFound' => 'error',
            'NonPrefixedConstantFound' => 'error|warning',
            'NonPrefixedEnumFound' => 'error',
            'NonPrefixedFunctionFound' => 'error',
            'NonPrefixedHooknameFound' => 'error|warning',
            'NonPrefixedInterfaceFound' => 'error',
            'NonPrefixedNamespaceFound' => 'error',
            'NonPrefixedSyntaxFound' => 'error',
            'NonPrefixedTraitFound' => 'error',
            'NonPrefixedVariableFound' => 'error|warning',
            'ShortPrefixPassed' => 'error',
            'VariableConstantNameFound' => 'error|warning',
        ],
        'WordPress.NamingConventions.ValidFunctionName' => [
            'FunctionDoubleUnderscore' => 'error',
            'FunctionNameInvalid' => 'error',
            'MethodDoubleUnderscore' => 'error',
            'MethodNameInvalid' => 'error',
        ],
        'WordPress.NamingConventions.ValidHookName' => [
            'NotLowercase' => 'error',
            'UseUnderscores' => 'warning',
        ],
        'WordPress.NamingConventions.ValidPostTypeSlug' => [
            'Empty' => 'error',
            'InvalidCharacters' => 'error',
            'NotStringLiteral' => 'warning',
            'PartiallyDynamic' => 'warning',
            'Reserved' => 'error',
            'ReservedPrefix' => 'error',
            'TooLong' => 'error',
        ],
        'WordPress.NamingConventions.ValidVariableName' => [
            'InterpolatedVariableNotSnakeCase' => 'error',
            'PropertyNotSnakeCase' => 'error',
            'UsedPropertyNotSnakeCase' => 'error',
            'VariableNotSnakeCase' => 'error',
        ],
        'WordPress.PHP.DevelopmentFunctions' => [
            'error_log_*' => 'warning',
            'prevent_path_disclosure_*' => 'warning',
        ],
        'WordPress.PHP.DiscouragedPHPFunctions' => [
            'obfuscation_*' => 'warning',
            'runtime_configuration_*' => 'warning',
            'serialize_*' => 'warning',
            'system_calls_*' => 'warning',
            'urlencode_*' => 'warning',
        ],
        'WordPress.PHP.DontExtract' => [
            'extract_*' => 'error',
        ],
        'WordPress.PHP.IniSet' => [
            '*_Disallowed' => 'error',
            'Risky' => 'warning',
        ],
        'WordPress.PHP.NoSilencedErrors' => [
            'Discouraged' => 'warning',
        ],
        'WordPress.PHP.PregQuoteDelimiter' => [
            'Missing' => 'warning',
        ],
        'WordPress.PHP.RestrictedPHPFunctions' => [
            'create_function_*' => 'error',
        ],
        'WordPress.PHP.StrictInArray' => [
            'FoundNonStrictFalse' => 'warning',
            'MissingTrueStrict' => 'warning',
        ],
        'WordPress.PHP.TypeCasts' => [
            'BinaryFound' => 'warning',
            'DoubleRealFound' => 'error',
            'UnsetFound' => 'error',
        ],
        'WordPress.PHP.YodaConditions' => [
            'NotYoda' => 'error',
        ],
        'WordPress.Security.EscapeOutput' => [
            'HeredocOutputNotEscaped' => 'error',
            'OutputNotEscaped' => 'error',
            'UnsafePrintingFunction' => 'error',
            'UnsafeSearchQuery' => 'error',
        ],
        'WordPress.Security.NonceVerification' => [
            'Missing' => 'error',
            'Recommended' => 'warning',
        ],
        'WordPress.Security.PluginMenuSlug' => [
            'Using__FILE__' => 'warning',
        ],
        'WordPress.Security.SafeRedirect' => [
            'wp_redirect_*' => 'warning',
        ],
        'WordPress.Security.ValidatedSanitizedInput' => [
            'InputNotSanitized' => 'error',
            'InputNotValidated' => 'error',
            'InputNotValidatedNotSanitized' => 'error',
            'MissingUnslash' => 'error',
        ],
        'WordPress.WP.AlternativeFunctions' => [
            'curl_*' => 'warning',
            'file_get_contents_*' => 'warning',
            'file_system_operations_*' => 'warning',
            'json_encode_*' => 'warning',
            'parse_url_*' => 'warning',
            'rand_*' => 'warning',
            'rand_seeding_*' => 'warning',
            'rename_*' => 'warning',
            'strip_tags_*' => 'warning',
            'unlink_*' => 'warning',
        ],
        'WordPress.WP.Capabilities' => [
            'Deprecated' => 'error|warning',
            'Invalid' => 'error',
            'RoleFound' => 'error',
            'Undetermined' => 'warning',
            'Unknown' => 'warning',
        ],
        'WordPress.WP.CapitalPDangit' => [
            'MisspelledClassName' => 'warning',
            'MisspelledInComment' => 'warning',
            'MisspelledInText' => 'warning',
            'MisspelledNamespaceName' => 'warning',
        ],
        'WordPress.WP.ClassNameCase' => [
            'Incorrect' => 'warning',
        ],
        'WordPress.WP.CronInterval' => [
            'ChangeDetected' => 'warning',
            'CronSchedulesInterval' => 'warning',
        ],
        'WordPress.WP.DeprecatedClasses' => [
            '*Found' => 'error|warning',
        ],
        'WordPress.WP.DeprecatedFunctions' => [
            '*Found' => 'error|warning',
        ],
        'WordPress.WP.DeprecatedParameterValues' => [
            'Found' => 'error|warning',
        ],
        'WordPress.WP.DeprecatedParameters' => [
            '*Param*Found' => 'error|warning',
        ],
        'WordPress.WP.DiscouragedConstants' => [
            '*DeclarationFound' => 'warning',
            '*UsageFound' => 'warning',
        ],
        'WordPress.WP.DiscouragedFunctions' => [
            'query_posts_*' => 'warning',
            'wp_reset_query_*' => 'warning',
        ],
        'WordPress.WP.EnqueuedResourceParameters' => [
            'MissingVersion' => 'warning',
            'NoExplicitVersion' => 'error',
            'NotInFooter' => 'warning',
        ],
        'WordPress.WP.EnqueuedResources' => [
            'NonEnqueuedScript' => 'error',
            'NonEnqueuedStylesheet' => 'error',
        ],
        'WordPress.WP.GetMetaSingle' => [
            'Missing' => 'warning',
        ],
        'WordPress.WP.GlobalVariablesOverride' => [
            'Prohibited' => 'error',
        ],
        'WordPress.WP.I18n' => [
            'EmptyTextDomain' => 'error',
            'InterpolatedVariable*' => 'error',
            'LowLevelTranslationFunction' => 'warning',
            'MismatchedPlaceholders' => 'warning',
            'MissingArg*' => 'error',
            'MissingArg*Default' => 'warning',
            'MissingSingularPlaceholder' => 'error',
            'MissingTranslatorsComment' => 'error',
            'MixedOrderedPlaceholders*' => 'error',
            'NoEmptyStrings' => 'error',
            'NoHtmlWrappedStrings' => 'warning',
            'NonSingularStringLiteral*' => 'error',
            'SingleUnderscoreGetTextFunction' => 'error',
            'SuperfluousDefaultTextDomain' => 'warning',
            'TextDomainMismatch' => 'error',
            'TooManyFunctionArgs' => 'error',
            'TranslatorsCommentWrongStyle' => 'error',
            'UnorderedPlaceholders*' => 'error',
        ],
        'WordPress.WP.PostsPerPage' => [
            'posts_per_page_*' => 'warning',
        ],
    ];

    private function __construct() {}
}
