#!/usr/bin/env bash
# Benchmarks phpcs (WordPress-Extra) against mago + this extension on a WordPress codebase.
#
#   bench/run.sh <project-dir> [<text-domain>] [<prefix>]
#
# Needs: vendor/bin/mago (composer install), php, perl, and a phpcs with WPCS on PATH or
# in $PHPCS (defaults to vendor/bin/phpcs of this package if installed). Results print as
# a markdown table; paste them into README.md.
#
# Not an apples-to-apples rule comparison: phpcs runs the full WordPress-Extra ruleset
# (WPCS 3.4.1), while mago only runs this extension's rules.
set -euo pipefail

[[ $# -ge 1 ]] || { echo "usage: bench/run.sh <project-dir> [<text-domain>] [<prefix>]" >&2; exit 1; }

project=$(cd "$1" && pwd -P)
domain=${2:-}
prefix=${3:-}
here=$(cd "$(dirname "$0")/.." && pwd -P)
mago=${MAGO:-$here/vendor/bin/mago}
phpcs=${PHPCS:-$here/vendor/bin/phpcs}

[[ -x "$mago" ]] || { echo "mago not found or not executable: $mago" >&2; exit 1; }
[[ -x "$phpcs" ]] || { echo "phpcs not found or not executable: $phpcs" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# TOML/XML basic-string escaping (JSON is generated by php -r below, which escapes itself).
toml_escape() { local s=${1//\\/\\\\}; printf '%s' "${s//\"/\\\"}"; }
xml_escape() {
    local s=${1//&/&amp;}
    s=${s//</&lt;}; s=${s//>/&gt;}; s=${s//\"/&quot;}
    printf '%s' "${s//\'/&apos;}"
}

printf 'php-version = "8.2"\n[source]\npaths = ["%s"]\nexcludes = ["**/vendor/**", "**/vendor_prefixed/**", "**/node_modules/**", "**/tests/**"]\n[linter]\nintegrations = ["wordpress"]\n[extension-hosts.wordpress]\ncommand = ["php", "%s"]\n' \
    "$(toml_escape "$project")" "$(toml_escape "$here/resources/worker.php")" > "$work/mago.toml"

php -r '
[, $domain, $prefix, $out] = $argv;
file_put_contents($out, json_encode(
    ["extra" => ["mago-wordpress" => ["text-domains" => [$domain], "prefixes" => [$prefix]]]],
    JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES,
) . "\n");
' "$domain" "$prefix" "$work/composer.json"

printf '<?xml version="1.0"?>\n<ruleset name="bench">\n  <rule ref="WordPress-Extra"/>\n  <rule ref="WordPress.WP.I18n"><properties><property name="text_domain" type="array"><element value="%s"/></property></properties></rule>\n  <rule ref="WordPress.NamingConventions.PrefixAllGlobals"><properties><property name="prefixes" type="array"><element value="%s"/></property></properties></rule>\n</ruleset>\n' \
    "$(xml_escape "$domain")" "$(xml_escape "$prefix")" > "$work/phpcs.xml"

codes=$(paste -sd, - < "$here/tests/corpus/expected-rules.txt")

# The worker discovers composer.json via getcwd(), so mago must run from $work.
run_mago() { (cd "$work" && "$mago" --config "$work/mago.toml" lint --only "$codes" --reporting-format code-count); }
run_phpcs() {
    "$phpcs" --standard="$work/phpcs.xml" --extensions=php \
        --ignore='*/vendor/*,*/vendor_prefixed/*,*/node_modules/*,*/tests/*' \
        --parallel=8 -d memory_limit=2G --report=summary "$project"
}

# A linter that finds issues exits 1; only that or 0 (clean) are acceptable outcomes.
run_checked() { # name, function
    local name=$1 fn=$2 status=0 out
    out=$("$fn" 2>&1) || status=$?
    if (( status != 0 && status != 1 )); then
        echo "error: $name exited with status $status:" >&2
        printf '%s\n' "$out" >&2
        exit 1
    fi
    printf '%s' "$out"
}

files=$(find "$project" -name '*.php' -not -path '*/vendor/*' -not -path '*/vendor_prefixed/*' -not -path '*/node_modules/*' -not -path '*/tests/*' | wc -l | tr -d ' ')
mago_version=$("$mago" --version 2>&1 | tail -1)
phpcs_version=$("$phpcs" --version 2>&1 | tail -1)

echo "## $(basename "$project") ($files PHP files)"
echo
echo "$mago_version / $phpcs_version"
echo
echo "mago issue counts by rule:"
run_checked mago run_mago
echo

# Mean of 3 timed runs after 1 warm-up (hyperfine hangs on mago's worker protocol). Each
# run is re-checked so a crash mid-benchmark fails the script instead of skewing the mean.
timed() { # name, function
    local name=$1 fn=$2 total=0 t0 t1
    run_checked "$name" "$fn" >/dev/null
    for _ in 1 2 3; do
        t0=$(perl -MTime::HiRes=time -e 'printf "%.3f", time')
        run_checked "$name" "$fn" >/dev/null
        t1=$(perl -MTime::HiRes=time -e 'printf "%.3f", time')
        total=$(perl -e "print $total + ($t1 - $t0)")
    done
    perl -e "printf \"| %s | %.2f s |\n\", '$name', $total / 3"
}
echo "| Tool | Mean of 3 runs |"
echo "|:---|---:|"
timed "phpcs WordPress-Extra (WPCS 3.4.1, --parallel=8)" run_phpcs
timed "mago + mago-wordpress" run_mago
